// data.jsx — funding opportunities, forum threads, and category configs.
// Used by all the sub-pages (Grants, Scholarships, Research, Forum, detail pages).

// ──────────────────────────────────────────────────────────────────────────
// CATEGORY CONFIGS — exactly the groups + items from the feature list.
const CATEGORY_CONFIG = {
  grants: {
    title: 'Business grants',
    description: 'Federal, provincial, and private grants for Canadian businesses — from startup capital to growth, R&D and exports.',
    groups: [
      { id:'source',  label:'Source',        items:[
        { id:'federal',    label:'Federal' },
        { id:'provincial', label:'Provincial' },
      ]},
      { id:'need',    label:'Business need', items:[
        { id:'startup',        label:'Startup' },
        { id:'growth',         label:'Growth' },
        { id:'financing',      label:'Financing' },
        { id:'export',         label:'Export' },
        { id:'digital',        label:'Digital' },
        { id:'innovation',     label:'Innovation' },
        { id:'equipment',      label:'Equipment' },
        { id:'sustainability', label:'Sustainability' },
      ]},
      { id:'support', label:'Support type',  items:[
        { id:'advisory', label:'Advisory' },
      ]},
      { id:'audience', label:'Audience',     items:[
        { id:'indigenous',           label:'Indigenous' },
        { id:'women',                label:'Women' },
        { id:'black-entrepreneurs',  label:'Black Entrepreneurs' },
        { id:'2slgbtqi',             label:'2SLGBTQI+' },
      ]},
    ],
  },

  scholarships: {
    title: 'Scholarships',
    description: 'Scholarships, bursaries and entrance awards for Canadian students — undergraduate to doctoral, federal to private.',
    groups: [
      { id:'source',   label:'Source',     items:[
        { id:'federal',    label:'Federal' },
        { id:'provincial', label:'Provincial' },
      ]},
      { id:'audience', label:'Audience',   items:[
        { id:'indigenous',    label:'Indigenous' },
        { id:'women',         label:'Women' },
        { id:'international', label:'International' },
      ]},
      { id:'award',    label:'Award type', items:[
        { id:'need-based',   label:'Need-based' },
        { id:'merit-based',  label:'Merit-based' },
        { id:'essay-prize',  label:'Essay / Prize' },
        { id:'entrance',     label:'Entrance' },
      ]},
      { id:'level',    label:'Study level',items:[
        { id:'graduate',      label:'Graduate' },
        { id:'undergraduate', label:'Undergraduate' },
      ]},
      { id:'field',    label:'Field',      items:[
        { id:'stem',        label:'STEM' },
        { id:'health',      label:'Health' },
        { id:'trades',      label:'Trades' },
        { id:'business',    label:'Business' },
        { id:'arts',        label:'Arts' },
        { id:'education',   label:'Education' },
        { id:'law-social',  label:'Law / Social Sciences' },
        { id:'environment', label:'Environment' },
        { id:'athletics',   label:'Athletics' },
      ]},
    ],
  },

  research: {
    title: 'Research funding',
    description: 'Tri-council operating grants, partnership programs and CFI infrastructure for Canadian academic researchers.',
    groups: [
      { id:'source', label:'Source',         items:[
        { id:'federal', label:'Federal' },
        { id:'nserc',   label:'NSERC' },
        { id:'sshrc',   label:'SSHRC' },
      ]},
      { id:'area',   label:'Research area',  items:[
        { id:'stem',            label:'STEM' },
        { id:'social-sciences', label:'Social Sciences' },
        { id:'environment',     label:'Environment' },
        { id:'quantum',         label:'Quantum' },
      ]},
      { id:'focus',  label:'Program focus',  items:[
        { id:'discovery',         label:'Discovery' },
        { id:'partnership',       label:'Partnership' },
        { id:'international',     label:'International' },
        { id:'applied',           label:'Applied Research' },
        { id:'equipment',         label:'Equipment' },
        { id:'training',          label:'Training' },
        { id:'equity',            label:'Equity / Diversity' },
        { id:'interdisciplinary', label:'Interdisciplinary' },
      ]},
    ],
  },
};

// ──────────────────────────────────────────────────────────────────────────
// FUNDING OPPORTUNITIES — diverse Canadian programs.
const FUNDING = [
  // ────── GRANTS ──────
  {
    id:'cdap', kind:'grants', title:'Canada Digital Adoption Program', provider:'ISED · Federal',
    description:'Up to $15,000 toward a digital adoption plan, plus an interest-free BDC loan to implement it.',
    amount:'$15,000', deadline:'Rolling', deadlineDays:9999,
    categories:['federal','digital','growth'], tags:['SME','Digital'],
    aiOverview:'A federal program supporting digital transformation for SMEs with 1–499 employees and $500K+ revenue. Pairs a $15K advisor-led plan with up to $100K in interest-free BDC financing.',
    goodFitFor:['Established SMEs (1–499 employees)','Revenue ≥ $500K/yr','Owners ready to adopt new technology'],
    eligibility:['For-profit Canadian business','At least one full-time employee','Demonstrated annual revenue'],
    requirements:['Digital needs assessment','Vetted advisor engagement','Implementation plan','Annual reporting'],
    aiChecklist:['Sales & inventory baseline','Tech stack inventory','Owner KPIs (3)','Advisor vetted on roster'],
    url:'#',
  },
  {
    id:'sred', kind:'grants', title:'Scientific Research & Experimental Development (SR&ED)', provider:'CRA · Federal',
    description:'Refundable tax credits for R&D labour, materials and overhead — up to 35% for CCPCs.',
    amount:'Up to 35% credit', deadline:'18 mo. after fiscal',  deadlineDays:540,
    categories:['federal','innovation','startup','growth'], tags:['R&D','Tax credit'],
    aiOverview:'CRA program refunding a portion of eligible R&D expenditures. CCPCs receive up to 35% refundable; other corps receive 15% non-refundable.',
    goodFitFor:['Pre-revenue & growth-stage CCPCs','Hardware & deep-tech startups','Process-improvement R&D'],
    eligibility:['Canadian corporation','Eligible R&D activity (uncertainty + advancement)','Records of expenditures'],
    requirements:['Form T661 + project descriptions','Time-tracking by project','Eligible expenditure ledger'],
    aiChecklist:['Hypothesis stated per project','Iteration log with dates','Salary allocation %','Materials consumed log'],
    url:'#',
  },
  {
    id:'irap', kind:'grants', title:'NRC IRAP — Innovation Assistance', provider:'NRC · Federal',
    description:'Non-repayable contribution for technical projects in SMEs, plus a national advisor network.',
    amount:'Up to $1,000,000', deadline:'Continuous', deadlineDays:9999,
    categories:['federal','innovation','advisory','growth'], tags:['Tech','Advisory'],
    aiOverview:'A national R&D contribution program with assigned Industrial Technology Advisors. Funds salaries & contractor costs for technical projects.',
    goodFitFor:['SMEs scaling a technical capability','Pre-Series-A startups','Hardware & cleantech'],
    eligibility:['Incorporated for-profit ≤ 500 employees','Growth-oriented business plan','Technical project with clear outcomes'],
    requirements:['Statement of work','Cost breakdown by quarter','Milestone reporting'],
    url:'#',
  },
  {
    id:'cansx', kind:'grants', title:'CanExport SMEs', provider:'Global Affairs Canada',
    description:'Up to $50,000 to enter new international markets — trade shows, market research, IP protection.',
    amount:'Up to $50,000', deadline:'Mar 15', deadlineDays:60,
    categories:['federal','export','growth'], tags:['Export','International'],
    aiOverview:'Covers up to 50% of eligible costs for entering one new export market. Per-application cap and reimbursement model.',
    goodFitFor:['SMEs with proven domestic traction','First-time exporters','Niche B2B products'],
    eligibility:['Incorporated in Canada','Annual revenue $100K–$100M','Fewer than 500 FTE'],
    requirements:['Target market plan','Activity-level budget','Reimbursement receipts'],
    url:'#',
  },
  {
    id:'oig', kind:'grants', title:'Ontario Innovation Grant', provider:'Ontario · Provincial',
    description:'Provincial top-up for tech adoption in manufacturing and processing sectors.',
    amount:'Up to $150,000', deadline:'Sep 30', deadlineDays:120,
    categories:['provincial','digital','equipment','growth'], tags:['Ontario','Mfg'],
    aiOverview:'Capital and training assistance for Ontario manufacturers adopting digital and automation technology.',
    goodFitFor:['Mid-sized Ontario manufacturers','Operations leaders modernizing lines'],
    eligibility:['Ontario HQ','NAICS 31–33','25+ FTE'],
    requirements:['Adoption plan','Vendor quotes','Productivity baseline'],
    url:'#',
  },
  {
    id:'wee', kind:'grants', title:'Women Entrepreneurship Strategy', provider:'ISED · Federal',
    description:'Funding and ecosystem support for women-led businesses across sectors and stages.',
    amount:'$25,000–$100,000', deadline:'Jun 30', deadlineDays:34,
    categories:['federal','women','startup','growth'], tags:['Women','Founders'],
    aiOverview:'Targeted funding plus regional ecosystem support to grow women-led businesses. Multiple streams by stage.',
    goodFitFor:['Women-identifying founders','50%+ women-owned businesses'],
    eligibility:['Majority women-owned','Canadian incorporated','Active operations'],
    requirements:['Stage-appropriate growth plan','Ownership documentation'],
    url:'#',
  },
  {
    id:'iaf', kind:'grants', title:'Indigenous Business Accelerator Fund', provider:'NACCA',
    description:'Capital, mentorship, and capacity support for Indigenous-owned businesses.',
    amount:'Up to $99,999', deadline:'Rolling', deadlineDays:9999,
    categories:['federal','indigenous','startup','growth','advisory'], tags:['Indigenous','Accelerator'],
    goodFitFor:['51%+ Indigenous-owned','Operating in Canada','Growth-stage'],
    eligibility:['Verified Indigenous ownership','Demonstrated revenue or strong business plan'],
    requirements:['Status documentation','Business plan + financials'],
    url:'#',
  },
  {
    id:'bsg', kind:'grants', title:'Black Entrepreneurship Loan Fund', provider:'FACE Coalition · Federal',
    description:'Affordable capital and mentorship for Black-led businesses, in partnership with BDC.',
    amount:'$25K–$250K', deadline:'Continuous', deadlineDays:9999,
    categories:['federal','black-entrepreneurs','financing','startup'], tags:['Black founders','Loan'],
    goodFitFor:['Black founders','Underserved sectors','Growth or early-stage businesses'],
    eligibility:['51%+ Black-owned','Canadian operations','Repayment capacity'],
    requirements:['Business plan','Financials & projections'],
    url:'#',
  },
  {
    id:'gcc', kind:'grants', title:'Green Construction through Wood (GCWood)', provider:'NRCan · Federal',
    description:'Funds projects using low-carbon wood construction to demonstrate climate-resilient design.',
    amount:'Up to $2,000,000', deadline:'Dec 31', deadlineDays:188,
    categories:['federal','sustainability','equipment'], tags:['Climate','Construction'],
    goodFitFor:['Construction & architecture firms','Developers piloting mass-timber'],
    eligibility:['Canadian project site','Verified GHG reduction model'],
    requirements:['Project plan with timeline','GHG quantification','Third-party verification plan'],
    url:'#',
  },
  {
    id:'queer', kind:'grants', title:'2SLGBTQI+ Entrepreneur Capacity Fund', provider:'Egale + ESDC',
    description:'Capacity and operating support for 2SLGBTQI+-led businesses and community ventures.',
    amount:'$10K–$75K', deadline:'May 31', deadlineDays:8,
    categories:['federal','2slgbtqi','startup','advisory'], tags:['2SLGBTQI+','Capacity'],
    goodFitFor:['2SLGBTQI+-led ventures','Community-serving businesses'],
    eligibility:['Self-identified 2SLGBTQI+ leadership','Active operations or strong launch plan'],
    requirements:['Operating plan','Capacity gap statement'],
    url:'#',
  },

  // ────── SCHOLARSHIPS ──────
  {
    id:'vanier', kind:'scholarships', title:'Vanier Canada Graduate Scholarship', provider:'Tri-Council · Federal',
    description:'$50,000/yr for three years for doctoral students at Canadian universities with high leadership potential.',
    amount:'$50,000/yr × 3', deadline:'Nov 2', deadlineDays:163,
    categories:['federal','graduate','merit-based','stem','health','law-social'], tags:['Doctoral','Leadership'],
    aiOverview:'A flagship Tri-council award for top doctoral scholars. Weighted equally on academic excellence, research potential and leadership.',
    goodFitFor:['Doctoral students starting in fall','Strong demonstrated leadership','Cross-council applicants'],
    eligibility:['Nominated by a Canadian university','Pursuing first doctoral degree','Completed ≤ 20 months at submission'],
    requirements:['Research proposal (2 pages)','Leadership statement','Two reference letters','University nomination'],
    aiChecklist:['Leadership examples (3)','Research keywords aligned to council','Reference assignments confirmed','Word counts checked'],
    url:'#',
  },
  {
    id:'pgsd', kind:'scholarships', title:'NSERC PGS-D Doctoral Scholarship', provider:'NSERC · Federal',
    description:'$23,000/year for up to 36 months for STEM doctoral students.',
    amount:'$23,000/yr', deadline:'Oct 14', deadlineDays:144,
    categories:['federal','graduate','merit-based','stem'], tags:['STEM','PhD'],
    goodFitFor:['STEM doctoral applicants','First-or-second-year doctoral students'],
    eligibility:['Canadian citizen or PR','Pursuing STEM doctoral degree','Avg ≥ A- in last 2 years'],
    requirements:['Research proposal','Transcripts','Two reference reports','University rank list'],
    url:'#',
  },
  {
    id:'ogs', kind:'scholarships', title:'Ontario Graduate Scholarship', provider:'Ontario · Provincial',
    description:'$15,000 per academic year for graduate students at participating Ontario universities.',
    amount:'$15,000', deadline:'Mar 1', deadlineDays:280,
    categories:['provincial','graduate','merit-based'], tags:['Ontario','Grad'],
    goodFitFor:['Master\'s and doctoral students in Ontario','Applicants with first-class average'],
    eligibility:['Studying at participating Ontario institution','Avg ≥ A- in last 2 years of study'],
    requirements:['University application portal','Transcripts','Reference letters'],
    url:'#',
  },
  {
    id:'loran', kind:'scholarships', title:'Loran Scholars Award', provider:'Loran Scholars Foundation',
    description:'$100,000 over four years for undergraduate students demonstrating character, service and leadership.',
    amount:'$100,000', deadline:'Oct 12', deadlineDays:142,
    categories:['undergraduate','merit-based','essay-prize'], tags:['Undergrad','Leadership'],
    goodFitFor:['Grade-12 students with strong service record','Future undergraduates at partner universities'],
    eligibility:['Canadian citizen, PR, or protected person','Entering first undergraduate degree','Minimum 85% average'],
    requirements:['Application essays','References','Interviews (regional + national)'],
    url:'#',
  },
  {
    id:'indspire', kind:'scholarships', title:'Indspire Building Brighter Futures', provider:'Indspire',
    description:'Bursaries, scholarships and awards for First Nations, Inuit and Métis students.',
    amount:'$1,500–$20,000', deadline:'Aug 1', deadlineDays:70,
    categories:['indigenous','need-based','merit-based','undergraduate','graduate'], tags:['Indigenous','Need + Merit'],
    goodFitFor:['Indigenous students at any post-secondary level','Trades, STEM, health and arts disciplines'],
    eligibility:['Self-identified First Nations, Inuit or Métis','Enrolled or accepted at post-secondary'],
    requirements:['Self-identification','Proof of enrollment','Personal statement'],
    url:'#',
  },
  {
    id:'wcs', kind:'scholarships', title:'Women in Engineering Scholarship', provider:'Engineers Canada',
    description:'Tuition support for women pursuing accredited undergraduate engineering programs.',
    amount:'$5,000', deadline:'Apr 30', deadlineDays:340,
    categories:['undergraduate','merit-based','women','stem'], tags:['Women','Engineering'],
    eligibility:['Self-identified woman','Enrolled in accredited engineering program','Min. B+ avg'],
    requirements:['Personal statement','Transcripts','Reference letter'],
    url:'#',
  },
  {
    id:'trudeau', kind:'scholarships', title:'Trudeau Foundation Doctoral Scholarship', provider:'Pierre Elliott Trudeau Foundation',
    description:'Up to $60,000/yr for doctoral students in the humanities and social sciences.',
    amount:'$60,000/yr × 3', deadline:'Dec 15', deadlineDays:206,
    categories:['federal','graduate','merit-based','law-social','arts'], tags:['Doctoral','Humanities'],
    goodFitFor:['Doctoral students in SSHRC fields','Public-engagement orientation'],
    eligibility:['Doctoral students in HSS','Demonstrated public engagement'],
    requirements:['Research proposal','Engagement statement','Reference letters'],
    url:'#',
  },
  {
    id:'tdes', kind:'scholarships', title:'TD Community Leadership Scholarship', provider:'TD Bank Group',
    description:'$70,000 over four years + paid summer employment for undergraduates with a community-impact track record.',
    amount:'$70,000', deadline:'Nov 15', deadlineDays:177,
    categories:['undergraduate','merit-based','essay-prize'], tags:['Undergrad','Community'],
    eligibility:['Final-year high-school student','Documented community-leadership work'],
    requirements:['Essays (3)','References','Interview'],
    url:'#',
  },
  {
    id:'qes', kind:'scholarships', title:'Queen Elizabeth Scholars (Advanced Scholars)', provider:'Universities Canada',
    description:'Funding for Canadian graduate students to undertake international research placements.',
    amount:'$15,000+ per placement', deadline:'Feb 28', deadlineDays:280,
    categories:['graduate','merit-based','international'], tags:['International','Grad'],
    eligibility:['Canadian graduate student','Host institution agreement'],
    requirements:['Research placement plan','Host letter of support'],
    url:'#',
  },
  {
    id:'rbc-future', kind:'scholarships', title:'RBC Future Launch Scholarship', provider:'RBC',
    description:'$1,500 for post-secondary students re-skilling, switching paths or returning to school.',
    amount:'$1,500', deadline:'May 1', deadlineDays:344,
    categories:['undergraduate','graduate','need-based','essay-prize'], tags:['Re-skilling','Open'],
    eligibility:['Canadian or PR','Enrolled at any Canadian post-secondary'],
    requirements:['Short personal-impact essay'],
    url:'#',
  },

  // ────── RESEARCH FUNDING ──────
  {
    id:'sshrc-insight', kind:'research', title:'SSHRC Insight Grant', provider:'SSHRC · Federal',
    description:'$7K–$400K over 2–5 years for established researchers in the social sciences and humanities.',
    amount:'$7K–$400K', deadline:'Oct 1', deadlineDays:131,
    categories:['federal','sshrc','social-sciences','discovery','interdisciplinary'], tags:['HSS','5-yr'],
    aiOverview:'SSHRC\'s flagship program for HSS researchers. Reviewers weight knowledge mobilization plans heavily; budget underspend in year 1 is a common red flag.',
    goodFitFor:['Established faculty in HSS','Multi-year theoretical projects','Knowledge mobilization–strong teams'],
    eligibility:['Affiliated with eligible Canadian institution','Hold PhD or equivalent','SSHRC-eligible subject'],
    requirements:['Detailed proposal','Knowledge mobilization plan','Budget justification','Track record narrative'],
    aiChecklist:['KMb plan strong','Budget realism check','Track-record narrative ≤ 4 pages','Reviewer fit confirmed'],
    url:'#',
  },
  {
    id:'sshrc-pdg', kind:'research', title:'SSHRC Partnership Development Grant', provider:'SSHRC · Federal',
    description:'$75K–$200K over 1–3 years to develop new research partnerships in HSS.',
    amount:'$75K–$200K', deadline:'Nov 15', deadlineDays:176,
    categories:['federal','sshrc','social-sciences','partnership'], tags:['Partnership','Develop'],
    goodFitFor:['Research teams building new external partnerships','Cross-sector teams (academic + community/industry)'],
    eligibility:['PI at eligible institution','Two or more partner organizations'],
    requirements:['Partnership plan','Letters of support','Budget'],
    url:'#',
  },
  {
    id:'nserc-discovery', kind:'research', title:'NSERC Discovery Grant', provider:'NSERC · Federal',
    description:'Long-term funding for individual or small-team research programs in natural sciences and engineering.',
    amount:'$25K–$100K/yr', deadline:'Nov 1', deadlineDays:163,
    categories:['federal','nserc','stem','discovery'], tags:['STEM','5-yr'],
    aiOverview:'Discovery Grants support ongoing programs of research. Renewal cycles emphasize originality and the training of HQP.',
    goodFitFor:['Faculty in NSE fields','HQP-training-strong labs'],
    eligibility:['Faculty appointment at eligible institution','Active NSE research program'],
    requirements:['Notification of Intent','Full proposal','HQP training plan'],
    url:'#',
  },
  {
    id:'nserc-alliance', kind:'research', title:'NSERC Alliance Grants', provider:'NSERC · Federal',
    description:'Co-funded research with industry partners to accelerate applied STEM outcomes.',
    amount:'$20K–$1M/yr', deadline:'Continuous', deadlineDays:9999,
    categories:['federal','nserc','stem','partnership','applied'], tags:['Industry','Applied'],
    goodFitFor:['Faculty with industry partners','Applied STEM programs'],
    eligibility:['Eligible NSERC researcher','Confirmed industry partner contribution'],
    requirements:['Joint proposal','Cash + in-kind partner commitment','Reporting plan'],
    url:'#',
  },
  {
    id:'cfi-jelf', kind:'research', title:'CFI John R. Evans Leaders Fund', provider:'CFI · Federal',
    description:'Infrastructure funding for early-career researchers to set up competitive labs.',
    amount:'$125,000+', deadline:'Feb 15', deadlineDays:267,
    categories:['federal','stem','equipment'], tags:['Infrastructure','Labs'],
    goodFitFor:['New faculty hires','Lab-based research programs'],
    eligibility:['Institution-nominated','Faculty appointment within 5 years'],
    requirements:['Equipment plan','Vendor quotes','Institutional cost match'],
    url:'#',
  },
  {
    id:'nfrf', kind:'research', title:'New Frontiers in Research Fund — Exploration', provider:'Tri-Council · Federal',
    description:'Funds high-risk, high-reward, interdisciplinary projects up to $250K over 2 years.',
    amount:'$125K/yr × 2', deadline:'Jan 31', deadlineDays:252,
    categories:['federal','interdisciplinary','discovery','equity'], tags:['High-risk','Interdisc.'],
    goodFitFor:['Cross-discipline teams','Untested research questions'],
    eligibility:['Two PIs from different disciplines','Eligible institutions'],
    requirements:['NOI','Full proposal','EDI plan'],
    url:'#',
  },
  {
    id:'cihr-pg', kind:'research', title:'CIHR Project Grant', provider:'CIHR · Federal',
    description:'Funds health-research projects across the spectrum from biomedical to population health.',
    amount:'Varies', deadline:'Sep 15', deadlineDays:115,
    categories:['federal','stem','discovery'], tags:['Health','Discovery'],
    goodFitFor:['Health-research PIs','Cross-pillar projects'],
    eligibility:['CIHR-eligible institution','PI with health research focus'],
    requirements:['Full proposal','Knowledge translation plan','Team CVs'],
    url:'#',
  },
  {
    id:'nfrf-int', kind:'research', title:'NFRF International Joint Initiative', provider:'Tri-Council · Federal',
    description:'Co-funded international research collaborations on global challenges.',
    amount:'$250K/yr × 3', deadline:'Apr 30', deadlineDays:340,
    categories:['federal','international','partnership','environment'], tags:['International','Global'],
    goodFitFor:['Teams with confirmed international partners','Globally relevant research questions'],
    eligibility:['Canadian PI + international partner','Cost-share commitment'],
    requirements:['Joint proposal','Memorandum of understanding'],
    url:'#',
  },
  {
    id:'apogee', kind:'research', title:'Canada First Research Excellence Fund (Apogée)', provider:'Tri-Council · Federal',
    description:'Large-scale funding to help Canadian universities lead globally in priority research areas.',
    amount:'$50M–$200M', deadline:'Jun 15', deadlineDays:24,
    categories:['federal','stem','quantum','partnership'], tags:['Excellence','Scale'],
    goodFitFor:['Institution-led consortia','Globally competitive priority areas'],
    eligibility:['Institution nomination','Sustained excellence record'],
    requirements:['Institutional strategy','Letters of partner support','Audit-ready budget'],
    url:'#',
  },
  {
    id:'tspf', kind:'research', title:'Tri-Agency EDI Capacity Building Grant', provider:'Tri-Council · Federal',
    description:'Supports institutional and research-team initiatives to build EDI capacity in academic research.',
    amount:'$25K–$200K', deadline:'Jul 15', deadlineDays:53,
    categories:['federal','equity','training','social-sciences'], tags:['EDI','Capacity'],
    goodFitFor:['EDI-focused teams or units','Institution-supported initiatives'],
    eligibility:['Eligible Tri-Agency institution','EDI-specific scope'],
    requirements:['Capacity-building plan','Evaluation framework'],
    url:'#',
  },
  {
    id:'quantum-ip', kind:'research', title:'NSERC Quantum Strategic Partnerships', provider:'NSERC · Federal',
    description:'Targeted funding for quantum research projects with industrial relevance.',
    amount:'$500K–$2M', deadline:'Mar 20', deadlineDays:300,
    categories:['federal','nserc','quantum','partnership','applied'], tags:['Quantum','Partnership'],
    goodFitFor:['Quantum-focused PIs','Industry-aligned research programs'],
    eligibility:['NSERC-eligible PI','Industry partner with cash share'],
    requirements:['Joint proposal','Industry cash + in-kind','Reporting plan'],
    url:'#',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// FORUM THREADS
const FORUM_THREADS = [
  {
    id:'cdap-advisor', title:'Anyone heard back about CDAP Stream 2 advisor reports?',
    author:'Hena P.', authorRole:'Business · Toronto', authorOnboarding:'Onboarded',
    category:'Funding', categoryKey:'funding',
    contentPreview:'We submitted in February and the advisor portal has been silent. Has anyone received their report back recently? Trying to figure out whether to nudge or wait.',
    content:'We submitted our Stream 2 application in February and the advisor portal has been silent for almost three months now. Our advisor confirmed receipt but we haven\'t had a status update since.\n\nFor anyone who\'s further along — how long did your report take? Did nudging through the portal help, or is it strictly first-come-first-served? We\'re trying to figure out whether to wait it out or escalate.',
    tags:['CDAP','Stream 2','Wait times'],
    replyCount:14, helpfulCount:22, date:'May 14, 2026', hot:true,
  },
  {
    id:'pgsd-template', title:'NSERC PGS-D writing template (round 4 winner)',
    author:'Dr. Marc S.', authorRole:'Researcher · UofT',
    category:'Research', categoryKey:'research',
    contentPreview:'I committee-reviewed PGS-D applications for four cycles. Here\'s the structural template I now coach my students with — three sections, two pages.',
    content:'I committee-reviewed PGS-D applications for four cycles. Here\'s the structural template I now coach my students with — three sections, two pages, with the reviewer rubric scoring beside each.\n\nSection 1: Research context (1/3 page). Lead with the problem, not the discipline. The reviewer scores "originality and significance" here — make it impossible to score below 5.\n\nSection 2: Methodology (1 page). The single biggest reason mid-band proposals get bumped is unclear methods.\n\nSection 3: HQP & training (1/3 page).',
    tags:['NSERC','PGS-D','Template','Doctoral'],
    replyCount:31, helpfulCount:48, date:'May 8, 2026',
  },
  {
    id:'sred-amortize', title:'Do I need to amortize prototype costs across years?',
    author:'Founder Q.', authorRole:'Business · Vancouver', authorOnboarding:'Onboarded',
    category:'Funding', categoryKey:'funding',
    contentPreview:'We built our prototype across two fiscal years with most material costs in year 1. Accountant says we can claim it all in year 2 — that doesn\'t sound right?',
    content:'We built our prototype across two fiscal years with most material costs in year 1. Accountant says we can claim it all in year 2 — that doesn\'t sound right to me. CRA T661 guidance suggests expenditures should be claimed in the year they\'re incurred.\n\nAnyone navigated this with their reviewer? Was there a workaround or did you just file an amended return?',
    tags:['SR&ED','Prototype','Accounting'],
    replyCount:7, helpfulCount:9, date:'May 19, 2026',
  },
  {
    id:'km-frame', title:'Best way to frame "knowledge mobilization" without sounding hollow',
    author:'Kira H.', authorRole:'Researcher · McGill',
    category:'Research', categoryKey:'research',
    contentPreview:'Reviewers seem to penalize KMb plans that are too generic but also reject the ones that are over-specific to one partner. Where\'s the sweet spot?',
    content:'Reviewers seem to penalize KMb plans that are too generic but also reject the ones that are over-specific to one partner. Where\'s the sweet spot?\n\nMy current draft has three audience tiers (academic / sectoral / public) with one output for each. Is that level of structure expected, or does it read as box-ticking?',
    tags:['SSHRC','KMb','Insight Grant'],
    replyCount:11, helpfulCount:15, date:'May 12, 2026',
  },
  {
    id:'collab-postdoc', title:'Looking for a postdoc collaborator — clinical NLP for population health',
    author:'Dr. Aman R.', authorRole:'Researcher · UBC',
    category:'Collaboration', categoryKey:'collaboration',
    contentPreview:'I have a CIHR-funded NLP project starting in September and a 2-year postdoc slot open. Looking for someone with clinical text experience.',
    content:'I have a CIHR-funded NLP project starting in September and a 2-year postdoc slot open. Looking for someone with clinical text experience and ideally one prior population-health publication.\n\nProject summary attached as an external link. Replies open via DM.',
    tags:['Postdoc','NLP','Health'],
    replyCount:4, helpfulCount:6, date:'May 20, 2026',
  },
  {
    id:'hiring-pm', title:'Hiring a part-time grant program manager (Toronto/remote)',
    author:'Mira L.', authorRole:'Business · Toronto', authorOnboarding:'Onboarded',
    category:'Hiring', categoryKey:'hiring',
    contentPreview:'We\'ve won three federal grants in the last 18 months and the reporting load has outpaced what I can do solo. Hiring a 0.4 FTE grant PM.',
    content:'We\'ve won three federal grants in the last 18 months and the reporting load has outpaced what I can do solo. Hiring a 0.4 FTE grant PM, ideally with SR&ED and IRAP reporting experience.\n\nFully remote in Canada. Compensation in JD link.',
    tags:['Hiring','Grant PM','Part-time'],
    replyCount:2, helpfulCount:3, date:'May 21, 2026',
  },
  {
    id:'ops-timesheets', title:'Time-tracking tools that survive a CRA audit?',
    author:'Sasha N.', authorRole:'Business · Calgary', authorOnboarding:'Onboarded',
    category:'Operations', categoryKey:'operations',
    contentPreview:'We\'re re-doing our SR&ED time-tracking after a near-miss in last year\'s review. Recommendations welcome — bonus if it doesn\'t hate our devs.',
    content:'We\'re re-doing our SR&ED time-tracking after a near-miss in last year\'s review. Recommendations welcome — bonus if it doesn\'t hate our devs. Currently between Harvest and an internal Notion + Linear workflow with weekly snapshot.\n\nWhat have audit-tested teams actually been using?',
    tags:['SR&ED','Tools','Time-tracking'],
    replyCount:9, helpfulCount:12, date:'May 17, 2026',
  },
  {
    id:'announce-mar', title:'Auctus update — Provincial coverage now live in BC, QC, NS',
    author:'Auctus team', authorRole:'Announcements',
    category:'Announcements', categoryKey:'announcements',
    contentPreview:'Three new provincial datasets indexed this week. BC, QC, NS are now refreshed daily with the same parser as the federal feed.',
    content:'Three new provincial datasets indexed this week. BC, QC, NS are now refreshed daily with the same parser as the federal feed. Full source list in the Sources page.\n\nLet us know if you find any missing programs — replies welcome.',
    tags:['Update','Coverage','Provincial'],
    replyCount:5, helpfulCount:18, date:'May 22, 2026',
  },
];

// Sample replies for thread detail
const FORUM_REPLIES = {
  'cdap-advisor': [
    { id:'r1', author:'Jaspreet K.', authorRole:'Business · Edmonton', authorOnboarding:'Onboarded', date:'May 16, 2026',
      content:'Ours took 11 weeks from submission to advisor report. Nudging through the portal didn\'t help — what worked was emailing the regional contact directly with our case ID in the subject line.',
      helpful: 12 },
    { id:'r2', author:'Tara M.', authorRole:'Business · Halifax', authorOnboarding:'Onboarded', date:'May 17, 2026',
      content:'+1 on the email approach. Also: confirm your advisor is still on the roster — ours had rolled off and we didn\'t find out until I asked.',
      helpful: 7 },
    { id:'r3', author:'Hena P.', authorRole:'Business · Toronto', authorOnboarding:'Onboarded', date:'May 18, 2026',
      content:'Thanks both — emailing today. Will reply with timing for anyone reading this later.',
      helpful: 3 },
  ],
  default: [
    { id:'rd1', author:'Auctus member', authorRole:'Community', authorOnboarding:'',
      date:'May 18, 2026',
      content:'Reply text shown here for the prototype. Replies retain author, role, date, content and a Helpful counter.',
      helpful: 4 },
  ],
};

Object.assign(window, { CATEGORY_CONFIG, FUNDING, FORUM_THREADS, FORUM_REPLIES });
